'use client'

import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { ResourceToolbar } from '@/components/resource-toolbar'
import { usePageState } from '@/components/page-state'
import { Dialog } from '@/components/dialog'
import { EmptyState } from '@/components/empty-state'
import { Icon } from '@/components/icons'
import { ConfirmButton } from '@/components/confirm-button'
import { apiFetch } from '@/lib/api-client'
import { notifyError } from '@/lib/notifications'
import type { ApplicationStatus, ExtractedApplication, JobApplication, JobRequirement } from '@/components/types'
import { formatApplicationStatus } from '@/lib/application-status'
import { formatShortDate } from '@/lib/date'

const formatStatus = formatApplicationStatus

const statuses: ApplicationStatus[] = ['Saved', 'Applied', 'HrInterview', 'TechnicalInterview', 'Offer', 'Rejected', 'Withdrawn']
const filters: Array<{ label: string; value: ApplicationStatus | 'All' }> = [{ label: 'All', value: 'All' }, { label: 'Saved', value: 'Saved' }, { label: 'Applied', value: 'Applied' }, { label: 'Interview', value: 'HrInterview' }, { label: 'Offer', value: 'Offer' }, { label: 'Rejected', value: 'Rejected' }, { label: 'Withdrawn', value: 'Withdrawn' }]
const formatDate = (value: string | null) => formatShortDate(value)
const toLocalInput = (value: string | null) => { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) }
const toUtc = (value: string) => value ? new Date(value).toISOString() : null
type RequirementDraft = { key: number; name: string; isRequired: boolean }
type ApplicationDraft = { company: string; position: string; jobUrl: string; location: string; salary: string; status: ApplicationStatus; appliedAt: string; interviewAt: string; notes: string; jobDescription: string; requirements: RequirementDraft[] }
type ApplicationInput = Omit<ApplicationDraft, 'salary' | 'appliedAt' | 'interviewAt' | 'requirements' | 'jobUrl' | 'location' | 'notes' | 'jobDescription'> & { salary: number | null; appliedAt: string | null; interviewAt: string | null; jobUrl: string | null; location: string | null; notes: string | null; jobDescription: string | null; requirements: Array<Pick<JobRequirement, 'name' | 'isRequired'>> }
const emptyDraft = (): ApplicationDraft => ({ company: '', position: '', jobUrl: '', location: '', salary: '', status: 'Saved', appliedAt: '', interviewAt: '', notes: '', jobDescription: '', requirements: [] })
const draftFromExtracted = (value: ExtractedApplication): ApplicationDraft => ({ company: value.company ?? '', position: value.position ?? '', jobUrl: value.jobUrl ?? '', location: value.location ?? '', salary: value.salary?.toString() ?? '', status: statuses.includes(value.status as ApplicationStatus) ? value.status as ApplicationStatus : 'Saved', appliedAt: toLocalInput(value.appliedAt), interviewAt: toLocalInput(value.interviewAt), notes: value.notes ?? '', jobDescription: value.jobDescription ?? '', requirements: value.requirements.map((requirement, index) => ({ key: -(index + 1), name: requirement.name, isRequired: requirement.isRequired })) })
const draftFrom = (item: JobApplication): ApplicationDraft => ({ company: item.company, position: item.position, jobUrl: item.jobUrl ?? '', location: item.location ?? '', salary: item.salary?.toString() ?? '', status: item.status, appliedAt: toLocalInput(item.appliedAt), interviewAt: toLocalInput(item.interviewAt), notes: item.notes ?? '', jobDescription: item.jobDescription ?? '', requirements: item.requirements.map(requirement => ({ key: requirement.id, name: requirement.name, isRequired: requirement.isRequired })) })
const inputFrom = (draft: ApplicationDraft): ApplicationInput => ({ company: draft.company.trim(), position: draft.position.trim(), status: draft.status, jobUrl: draft.jobUrl.trim() || null, location: draft.location.trim() || null, salary: draft.salary.trim() ? Number(draft.salary) : null, appliedAt: toUtc(draft.appliedAt), interviewAt: toUtc(draft.interviewAt), notes: draft.notes.trim() || null, jobDescription: draft.jobDescription.trim() || null, requirements: draft.requirements.map(({ name, isRequired }) => ({ name: name.trim(), isRequired })) })

export default function ApplicationsPage() {
  const router = useRouter(); const params = useSearchParams(); const client = useQueryClient(); const nextRequirementKey = useRef(-1)
  const [filter, setFilter] = useState<ApplicationStatus | 'All'>('All'); const [search, setSearch] = useState(params.get('search') ?? ''); const [open, setOpen] = useState(params.get('new') === '1'); const [editing, setEditing] = useState<JobApplication | null>(null); const [viewing, setViewing] = useState<JobApplication | null>(null); const [viewingOpen, setViewingOpen] = useState(false); const [draft, setDraft] = useState<ApplicationDraft>(emptyDraft); const [error, setError] = useState<string | null>(null); const [aiFillOpen, setAiFillOpen] = useState(false); const [aiText, setAiText] = useState(''); const [aiPending, setAiPending] = useState(false)
  useEffect(() => { if (params.get('new') !== '1') return; const timer = window.setTimeout(() => { const storedDraft = sessionStorage.getItem('careeros:application-draft'); if (storedDraft) { try { setDraft(draftFromExtracted(JSON.parse(storedDraft) as ExtractedApplication)); sessionStorage.removeItem('careeros:application-draft') } catch { sessionStorage.removeItem('careeros:application-draft') } } setOpen(true) }, 0); return () => window.clearTimeout(timer) }, [params])
  useEffect(() => { if (open) return; const timer = window.setTimeout(() => setEditing(null), 300); return () => window.clearTimeout(timer) }, [open])
  useEffect(() => { if (viewingOpen || !viewing) return; const timer = window.setTimeout(() => setViewing(null), 300); return () => window.clearTimeout(timer) }, [viewingOpen, viewing])
  const query = useQuery({ queryKey: ['applications'], queryFn: ({ signal }) => apiFetch<JobApplication[]>('/api/job-applications', { signal }) }); const items = useMemo(() => query.data ?? [], [query.data]); const count = (status: ApplicationStatus) => items.filter(item => item.status === status).length
  const [sort, setSort] = useState('updated')
  const visible = useMemo(() => items.filter(item => { const statusMatches = filter === 'All' || item.status === filter || (filter === 'HrInterview' && item.status === 'TechnicalInterview'); const term = search.trim().toLowerCase(); return statusMatches && (!term || `${item.company} ${item.position} ${item.location ?? ''}`.toLowerCase().includes(term)) }).sort((a, b) => {
    if (sort === 'company') return a.company.localeCompare(b.company) || a.position.localeCompare(b.position)
    if (sort === 'role') return a.position.localeCompare(b.position)
    if (sort === 'status') return statuses.indexOf(a.status) - statuses.indexOf(b.status)
    if (sort === 'salary') return (b.salary ?? -1) - (a.salary ?? -1)
    const field = sort === 'applied' ? 'appliedAt' : sort === 'interview' ? 'interviewAt' : 'updatedAt'
    if (!a[field]) return b[field] ? 1 : 0
    if (!b[field]) return -1
    return sort === 'interview' ? Date.parse(a[field]) - Date.parse(b[field]) : Date.parse(b[field]) - Date.parse(a[field])
  }), [filter, items, search, sort])
  const close = () => { setOpen(false); setError(null); setAiFillOpen(false); if (params.get('new') === '1') router.replace('/applications') }; const openCreate = () => { setEditing(null); setDraft(emptyDraft()); setError(null); setAiText(''); setAiFillOpen(false); setOpen(true) }; const openEdit = (item: JobApplication) => { setEditing(item); setDraft(draftFrom(item)); setError(null); setAiText(''); setAiFillOpen(false); setOpen(true) }; const openView = (item: JobApplication) => { setViewing(item); setViewingOpen(true) }; const closeView = () => setViewingOpen(false)
  const update = <K extends keyof ApplicationDraft>(key: K, value: ApplicationDraft[K]) => setDraft(current => ({ ...current, [key]: value })); const updateRequirement = (key: number, field: 'name' | 'isRequired', value: string | boolean) => setDraft(current => ({ ...current, requirements: current.requirements.map(requirement => requirement.key === key ? { ...requirement, [field]: value } : requirement) }))
  const fillWithAi = async () => { if (aiText.trim().length < 1 && draft.jobUrl.trim().length < 1) { notifyError('Paste job details or enter a readable job posting URL first.', 'Application extraction unavailable'); return }; setAiPending(true); try { const result = await apiFetch<{ application: ExtractedApplication }>('/api/ai/application-extract', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: aiText, url: draft.jobUrl.trim() || null }) }); const extracted = result.application; setDraft(current => ({ ...current, company: extracted.company || current.company, position: extracted.position || current.position, jobUrl: extracted.jobUrl || current.jobUrl, location: extracted.location || current.location, salary: extracted.salary === null ? current.salary : String(extracted.salary), appliedAt: extracted.appliedAt ? toLocalInput(extracted.appliedAt) : current.appliedAt, interviewAt: extracted.interviewAt ? toLocalInput(extracted.interviewAt) : current.interviewAt, jobDescription: extracted.jobDescription || current.jobDescription, notes: extracted.notes || current.notes, requirements: extracted.requirements.length ? extracted.requirements.map((requirement, index) => ({ key: -(index + 1), name: requirement.name, isRequired: requirement.isRequired })) : current.requirements })); setAiFillOpen(false); setAiText('') } catch { } finally { setAiPending(false) } }
  const save = useMutation({ mutationFn: async ({ id, input }: { id: number | null; input: ApplicationInput }) => { if (id === null) return apiFetch<JobApplication>('/api/job-applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); await apiFetch<void>(`/api/job-applications/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); return null }, onSuccess: (created, { id, input }) => { client.setQueryData<JobApplication[]>(['applications'], (previous = []) => id === null && created ? [created, ...previous] : previous.map(item => item.id === id ? { ...item, ...input, updatedAt: new Date().toISOString(), requirements: input.requirements.map((requirement, index) => ({ ...requirement, id: item.requirements[index]?.id ?? -(index + 1) })) } : item)); close(); void Promise.all([client.invalidateQueries({ queryKey: ['applications'] }), client.invalidateQueries({ queryKey: ['dashboard'] }), client.invalidateQueries({ queryKey: ['job-match'] })]) }, onError: (cause: Error) => setError(cause.message) })
  const remove = useMutation({ mutationFn: (id: number) => apiFetch<void>(`/api/job-applications/${id}`, { method: 'DELETE' }), onMutate: async id => { await client.cancelQueries({ queryKey: ['applications'] }); const previous = client.getQueryData<JobApplication[]>(['applications']); client.setQueryData<JobApplication[]>(['applications'], (current = []) => current.filter(item => item.id !== id)); return { previous } }, onError: (cause: Error, _id, context) => { if (context?.previous) client.setQueryData(['applications'], context.previous) }, onSettled: () => { void Promise.all([client.invalidateQueries({ queryKey: ['applications'] }), client.invalidateQueries({ queryKey: ['dashboard'] })]) } })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (draft.appliedAt && draft.interviewAt && draft.interviewAt < draft.appliedAt) { setError('Interview date and time cannot be earlier than the application date and time.'); return } if (draft.requirements.some(requirement => requirement.name.trim().length < 2)) { setError('Each requirement needs a name of at least two characters.'); return } save.mutate({ id: editing?.id ?? null, input: inputFrom(draft) }) }

  const pageState = usePageState([query], 'Loading your applications')
  if (pageState) return pageState

  return <>
    <section className="page-heading"><div><p className="eyebrow">OPPORTUNITY TRACKER</p><h1>Job applications</h1><p>Track roles and next steps.</p></div><button className="button button-primary" type="button" onClick={openCreate}><Icon name="plus" />Add application</button></section>
    <ResourceToolbar search={search} onSearch={setSearch} searchLabel="Search company, role or location" filterLabel="Application status" filters={filters.map(option => ({ ...option, count: option.value === 'All' ? items.length : option.value === 'HrInterview' ? count('HrInterview') + count('TechnicalInterview') : count(option.value) }))} filter={filter} onFilter={value => setFilter(value as ApplicationStatus | 'All')} sort={sort} onSort={setSort} sortOptions={[{value:'updated',label:'Recently updated'},{value:'company',label:'Company A–Z'},{value:'role',label:'Role A–Z'},{value:'status',label:'Pipeline stage'},{value:'applied',label:'Recently applied'},{value:'interview',label:'Interview date'},{value:'salary',label:'Highest salary'}]} count={visible.length} total={items.length} onReset={search || filter !== 'All' ? () => { setSearch(''); setFilter('All') } : undefined}/>

    <section className="compact-metrics application-metrics"><article><span className="soft-icon blue"><Icon name="briefcase" /></span><div className="metric-copy"><p>Total</p></div><strong className="metric-value">{items.length}</strong></article><article><span className="soft-icon violet"><Icon name="user" /></span><div className="metric-copy"><p>Interview</p></div><strong className="metric-value">{count('HrInterview') + count('TechnicalInterview')}</strong></article><article><span className="soft-icon amber"><Icon name="target" /></span><div className="metric-copy"><p>Offers</p></div><strong className="metric-value">{count('Offer')}</strong></article><article><span className="soft-icon teal"><Icon name="check" /></span><div className="metric-copy"><p>Applied</p></div><strong className="metric-value">{count('Applied')}</strong></article></section>
    <section className="resource-table-panel application-list-panel"><p className="table-scroll-hint">Scroll horizontally to see all columns</p>{visible.length ? <div className="data-table application-table" role="region" aria-label="Applications" tabIndex={0}><table role="table"><caption className="sr-only">Tracked applications and their current status</caption><thead><tr><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Dates</th><th scope="col">Actions</th></tr></thead><tbody role="rowgroup">{visible.map(item => <tr role="row" key={item.id}><td role="cell" data-label="Company"><span className="cell-stack"><strong title={item.company}>{item.company}</strong><span className="application-role" title={item.position}>{item.position}</span>{item.location && <small title={item.location}>{item.location}</small>}</span></td><td role="cell" data-label="Status"><span className={`status-pill ${item.status}`}>{formatStatus(item.status)}</span></td><td role="cell" data-label="Dates"><span className="cell-stack cell-dates"><span><small>Applied</small> {formatDate(item.appliedAt)}</span><span><small>Interview</small> {formatDate(item.interviewAt)}</span></span></td><td role="cell" data-label="Actions" className="row-actions"><div className="application-action-list"><ConfirmButton className="icon-action danger" label={`Delete ${item.position} at ${item.company}`} onConfirm={() => remove.mutate(item.id)} /><button className="icon-action" type="button" onClick={() => openEdit(item)} aria-label={`Edit ${item.position} at ${item.company}`} title="Edit application"><Icon name="edit" size={17} /></button><button className="icon-action" type="button" onClick={() => openView(item)} aria-label={`View all details for ${item.position} at ${item.company}`} title="View all details"><Icon name="eye" size={17} /></button>{item.jobUrl && <a className="icon-action" href={item.jobUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open job posting for ${item.position}`} title="Open job posting"><Icon name="external" size={17} /></a>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon="briefcase" title={search || filter !== 'All' ? 'No applications match' : 'Track your first role'} description={search || filter !== 'All' ? 'Try a different status or search term.' : 'Add a role you are eyeing. CareerOS keeps the timeline, requirements and match score together.'} action={search || filter !== 'All' ? <button className="button button-ghost" type="button" onClick={() => { setSearch(''); setFilter('All') }}>Clear filters</button> : <button className="button button-primary" type="button" onClick={openCreate}><Icon name="plus" size={17}/>Add application</button>} />}</section>
    <Dialog
      key={editing ? `edit-${editing.id}` : 'create'}
      open={open}
      onClose={close}
      wide
      eyebrow={editing ? 'APPLICATION DETAILS' : 'NEW OPPORTUNITY'}
      title={editing ? `Edit ${editing.position}` : 'Add an application'}
      description="Keep the role, timeline and requirements together so matching stays accurate."
      footer={<div className="dialog-actions">{editing && <Link className="button button-ghost" href={`/job-analyzer?applicationId=${editing.id}`}>Analyze match</Link>}<button className="button button-ghost" type="button" onClick={close}>Cancel</button><button className="button button-primary" type="submit" form="application-dialog-form" disabled={save.isPending}>{save.isPending ? 'Saving…' : editing ? 'Save changes' : 'Add application'}</button></div>}
    >
      <form id="application-dialog-form" className="dialog-form application-form" onSubmit={submit}>
        <div className="ai-fill-tools">
          <button className="button button-ghost" type="button" aria-expanded={aiFillOpen} onClick={() => setAiFillOpen(current => !current)}><Icon name="sparkles" size={16} />Fill with AI</button>
          {aiFillOpen && <div className="ai-fill-panel" data-open="true"><label>Paste the job posting<textarea value={aiText} maxLength={30000} onChange={event => setAiText(event.target.value)} placeholder="Paste text copied from LinkedIn, Indeed, or another job board..." /></label><button className="button button-primary" type="button" onClick={fillWithAi} disabled={aiPending}>{aiPending ? 'Extracting…' : 'Extract application fields'}<Icon name="arrow" size={15} /></button></div>}
        </div>
        {error && <div className="form-error" role="alert">{error}</div>}
        <div className="form-grid"><label>Company<input required minLength={2} maxLength={150} value={draft.company} onChange={event => update('company', event.target.value)} placeholder="Northstar Labs" /></label><label>Position<input required minLength={2} maxLength={150} value={draft.position} onChange={event => update('position', event.target.value)} placeholder="Backend developer" /></label></div>
        <div className="form-grid"><label>Location<input maxLength={150} value={draft.location} onChange={event => update('location', event.target.value)} placeholder="Remote · Berlin" /></label><label>Salary<input type="number" min="0" max="10000000" step="0.01" value={draft.salary} onChange={event => update('salary', event.target.value)} placeholder="Optional" /></label></div>
        <div className="form-grid"><label>Status<select value={draft.status} onChange={event => update('status', event.target.value as ApplicationStatus)}>{statuses.map(status => <option key={status} value={status}>{formatStatus(status)}</option>)}</select></label><label>Job posting URL<input type="url" maxLength={2048} value={draft.jobUrl} onChange={event => update('jobUrl', event.target.value)} placeholder="https://..." /></label></div>
        <div className="form-grid"><label>Applied date &amp; time<input type="datetime-local" value={draft.appliedAt} onChange={event => update('appliedAt', event.target.value)} /></label><label>Interview date &amp; time<input type="datetime-local" min={draft.appliedAt || undefined} value={draft.interviewAt} onChange={event => update('interviewAt', event.target.value)} /></label></div>
        <label>Job description<textarea maxLength={3000} value={draft.jobDescription} onChange={event => update('jobDescription', event.target.value)} placeholder="Paste the job description here..." /></label>
        <label>Notes<textarea maxLength={3000} value={draft.notes} onChange={event => update('notes', event.target.value)} placeholder="Contacts, follow-up dates, next steps..." /></label>
        <fieldset className="requirements-editor"><legend>Required skills and qualifications</legend><p>Mark each requirement as required or optional to keep matching clear. Maximum 50 requirements.</p>{draft.requirements.map(requirement => <div className="requirement-row" key={requirement.key}><label>Skill or qualification<input required minLength={2} maxLength={100} value={requirement.name} onChange={event => updateRequirement(requirement.key, 'name', event.target.value)} placeholder="ASP.NET Core" /></label><label className="requirement-required switch-field"><input className="switch" type="checkbox" role="switch" checked={requirement.isRequired} onChange={event => updateRequirement(requirement.key, 'isRequired', event.target.checked)} /><span>{requirement.isRequired ? 'Required' : 'Optional'}</span></label><button className="icon-action danger" type="button" aria-label={`Remove ${requirement.name || 'requirement'}`} onClick={() => update('requirements', draft.requirements.filter(entry => entry.key !== requirement.key))}><Icon name="trash" size={17} /></button></div>)}<button className="button button-ghost requirement-add" type="button" disabled={draft.requirements.length >= 50} onClick={() => { if (draft.requirements.length >= 50) { setError('An application can have up to 50 requirements.'); return } update('requirements', [...draft.requirements, { key: nextRequirementKey.current--, name: '', isRequired: true }]) }}><Icon name="plus" size={17} />Add requirement</button></fieldset>
        {editing && <p className="application-meta">Created {formatDate(editing.createdAt)} · Last updated {formatDate(editing.updatedAt)}</p>}
      </form>
    </Dialog>
    {viewing && <Dialog
      open={viewingOpen}
      onClose={closeView}
      wide
      eyebrow="APPLICATION DETAILS"
      title={`${viewing.position} at ${viewing.company}`}
      description="Review the complete application record."
      footer={<div className="dialog-actions"><button className="button button-ghost" type="button" onClick={closeView}>Close</button><button className="button button-primary" type="button" onClick={() => { const item = viewing; closeView(); window.setTimeout(() => { setViewing(null); openEdit(item) }, 300) }}><Icon name="edit" size={16} />Edit application</button></div>}
    >
      <div className="application-details">
        <div className="application-details-grid"><div><span>Company</span><strong>{viewing.company}</strong></div><div><span>Position</span><strong>{viewing.position}</strong></div><div><span>Status</span><strong>{formatStatus(viewing.status)}</strong></div><div><span>Location</span><strong>{viewing.location || '–'}</strong></div><div><span>Salary</span><strong>{viewing.salary === null ? '–' : viewing.salary.toLocaleString()}</strong></div><div><span>Applied</span><strong>{formatDate(viewing.appliedAt)}</strong></div><div><span>Interview</span><strong>{formatDate(viewing.interviewAt)}</strong></div><div><span>Created</span><strong>{formatDate(viewing.createdAt)}</strong></div></div>
        {viewing.jobUrl && <a className="application-detail-link" href={viewing.jobUrl} target="_blank" rel="noopener noreferrer"><Icon name="external" size={15} />Open job posting</a>}
        {viewing.jobDescription && <section><h3>Job description</h3><p>{viewing.jobDescription}</p></section>}
        {viewing.notes && <section><h3>Notes</h3><p>{viewing.notes}</p></section>}
        <section><h3>Required skills and qualifications</h3>{viewing.requirements.length ? <ul className="application-requirements">{viewing.requirements.map(requirement => <li key={requirement.id}><span>{requirement.name}</span><small>{requirement.isRequired ? 'Required' : 'Optional'}</small></li>)}</ul> : <p>No requirements added.</p>}</section>
      </div>
    </Dialog>}
  </>
}
