'use client'
import { useEffect,useMemo,useState,type FormEvent } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { useRouter,useSearchParams } from 'next/navigation'
import { Dialog } from '@/components/dialog'
import { EmptyState } from '@/components/empty-state'
import { Icon } from '@/components/icons'
import { apiFetch } from '@/lib/api-client'
import type { Project,Skill } from '@/components/types'

export default function ProjectsPage(){
 const router=useRouter(),params=useSearchParams(),client=useQueryClient();const[search,setSearch]=useState(params.get('search')??'');const[open,setOpen]=useState(params.get('new')==='1');const[editing,setEditing]=useState<Project|null>(null);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[repo,setRepo]=useState('');const[live,setLive]=useState('');const[skillIds,setSkillIds]=useState<number[]>([]);const[error,setError]=useState<string|null>(null);const[listError,setListError]=useState<string|null>(null)
 const projectsQ=useQuery({queryKey:['projects'],queryFn:()=>apiFetch<Project[]>('/api/projects')});const skillsQ=useQuery({queryKey:['skills'],queryFn:()=>apiFetch<Skill[]>('/api/skills')});const projects=useMemo(()=>projectsQ.data??[],[projectsQ.data]),skills=useMemo(()=>skillsQ.data??[],[skillsQ.data])
 function openCreate(){setEditing(null);setTitle('');setDescription('');setRepo('');setLive('');setSkillIds([]);setError(null);setOpen(true)}
 useEffect(()=>{if(params.get('new')!=='1')return;const timer=window.setTimeout(()=>openCreate(),0);return()=>window.clearTimeout(timer)},[params])
 function openEdit(p:Project){setEditing(p);setTitle(p.title);setDescription(p.description);setRepo(p.repositoryUrl??'');setLive(p.liveUrl??'');setSkillIds(p.skills.map(s=>s.id));setError(null);setOpen(true)}
 function close(){setOpen(false);setEditing(null);setError(null);if(params.get('new')==='1')router.replace('/projects')}
 const save=useMutation({
  mutationFn:async({id,payload}:{id:number|null;payload:{title:string;description:string;repositoryUrl:string|null;liveUrl:string|null;skillIds:number[]}})=>id===null
   ? apiFetch<Project>('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})
   : apiFetch<void>(`/api/projects/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),
  onSuccess:(created,{id,payload})=>{client.setQueryData<Project[]>(['projects'],(previous=[])=>id===null&&created?[created,...previous]:previous.map(project=>project.id===id?{...project,...payload,skills:payload.skillIds.map(skillId=>skills.find(skill=>skill.id===skillId)).filter((skill):skill is Skill=>Boolean(skill)),updatedAtUtc:new Date().toISOString()}:project));close();void Promise.all([client.invalidateQueries({queryKey:['projects']}),client.invalidateQueries({queryKey:['dashboard']})])},
  onError:(cause:Error)=>setError(cause.message),
 })
 const del=useMutation({
  mutationFn:(id:number)=>apiFetch<void>(`/api/projects/${id}`,{method:'DELETE'}),
  onMutate:async(id)=>{setListError(null);await client.cancelQueries({queryKey:['projects']});const previous=client.getQueryData<Project[]>(['projects']);client.setQueryData<Project[]>(['projects'],(current=[])=>current.filter(project=>project.id!==id));return{previous}},
  onError:(cause:Error,_id,context)=>{if(context?.previous)client.setQueryData(['projects'],context.previous);setListError(cause.message)},
  onSettled:()=>{void Promise.all([client.invalidateQueries({queryKey:['projects']}),client.invalidateQueries({queryKey:['dashboard']})])},
 })
 const visible=useMemo(()=>{const t=search.trim().toLowerCase();return projects.filter(p=>!t||`${p.title} ${p.description}`.toLowerCase().includes(t))},[projects,search]);const toggle=(id:number)=>setSkillIds(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(title.trim().length<2||description.trim().length<10)return;save.mutate({id:editing?.id??null,payload:{title:title.trim(),description:description.trim(),repositoryUrl:repo.trim()||null,liveUrl:live.trim()||null,skillIds}})}
 return <>
  <section className="page-heading"><div><p className="eyebrow">PROOF OF WORK</p><h1>Projects</h1><p>Showcase what you built and connect it to the skills you used.</p></div><button className="button button-primary" type="button" onClick={openCreate}><Icon name="plus"/>Add project</button></section>
  <div className="resource-toolbar project-toolbar"><div className="project-count"><strong>{projects.length}</strong><span>{projects.length===1?'project':'projects'} in your evidence library</span></div><label className="inline-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects" aria-label="Search projects"/></label></div>
  {(projectsQ.error||listError)&&<div className="error-banner" role="alert">{listError??projectsQ.error?.message}</div>}
  {projectsQ.isPending?<div className="project-list content-skeleton"><i/><i/><i/></div>:visible.length?<section className="project-list">{visible.map((p,index)=><article className="project-card" key={p.id}><div className={`project-art project-preview art-${index%3}`}>{p.liveUrl&&<iframe className="project-live-preview" src={p.liveUrl} title={`${p.title} live preview`} loading="lazy" scrolling="no" tabIndex={-1}/>} {!p.liveUrl&&<Icon name="folder" size={32}/>} {p.liveUrl&&<a className="project-live-link" href={p.liveUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${p.title} live site`} title="Open live site"><Icon name="external" size={17}/></a>}<span>{String(index+1).padStart(2,'0')}</span></div><div className="project-information"><div className="project-copy"><h2>{p.title}</h2><p>{p.description}</p><ul>{p.skills.map(s=><li key={s.id}>{s.name}</li>)}</ul></div><div className="project-actions"><div className="project-link-row"><button className="danger" type="button" onClick={()=>window.confirm(`Delete ${p.title}?`)&&del.mutate(p.id)} aria-label={`Delete ${p.title}`} title={`Delete ${p.title}`}><Icon name="trash" size={17}/></button><button className="project-edit-action" type="button" onClick={()=>openEdit(p)} aria-label={`Edit ${p.title}`} title={`Edit ${p.title}`}><Icon name="edit" size={17}/></button>{p.repositoryUrl&&<a href={p.repositoryUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${p.title} repository`} title="Open repository"><Icon name="graph" size={17}/></a>}</div></div></div></article>)}</section>:<section className="panel"><EmptyState title="No projects found" description={search?'Change your search term.':'Add a project to turn your skills into visible evidence.'}/></section>}
 <Dialog open={open} onClose={close} eyebrow={editing?'UPDATE EVIDENCE':'NEW EVIDENCE'} title={editing?`Edit ${editing.title}`:'Add a project'} description="Describe what you built and link the skills this project demonstrates."><form className="dialog-form" onSubmit={submit}>{error&&<div className="form-error">{error}</div>}<label>Project title<input required minLength={2} maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="CareerOS"/></label><label>Description<textarea required minLength={10} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What did you build?"/></label><div className="form-grid"><label>Repository URL<input type="url" value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/..."/></label><label>Live URL<input type="url" value={live} onChange={e=>setLive(e.target.value)} placeholder="https://..."/></label></div><fieldset className="skill-picker"><legend>Skills demonstrated</legend>{skills.length?<div>{skills.map(s=><label key={s.id} className={skillIds.includes(s.id)?'is-selected':''}><input type="checkbox" checked={skillIds.includes(s.id)} onChange={()=>toggle(s.id)}/><span>{s.name}</span></label>)}</div>:<p>Add skills first, then connect them to your project.</p>}</fieldset><div className="dialog-actions"><button className="button button-ghost" type="button" onClick={close}>Cancel</button><button className="button button-primary" type="submit" disabled={save.isPending}>{save.isPending?'Saving…':editing?'Save changes':'Add project'}</button></div></form></Dialog></>
}
