import {
  ArrowRight,
  Brain,
  BriefcaseBusiness,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ExternalLink,
  Eye,
  Folder,
  LayoutGrid,
  LogOut,
  Monitor,
  Moon,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Share2,
  Sparkles,
  Sun,
  Target,
  Trash2,
  UserRound,
  Waypoints,
  X,
} from 'lucide-react'

const icons = {
  arrow: ArrowRight,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  chart: ChartNoAxesColumnIncreasing,
  check: Check,
  chevron: ChevronDown,
  edit: Pencil,
  external: ExternalLink,
  eye: Eye,
  folder: Folder,
  graph: Network,
  grid: LayoutGrid,
  logout: LogOut,
  monitor: Monitor,
  moon: Moon,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  share: Share2,
  skillforge: Waypoints,
  sparkles: Sparkles,
  sun: Sun,
  target: Target,
  trash: Trash2,
  user: UserRound,
  x: X,
}

export type IconName = keyof typeof icons

export function Icon({ name, size = 20, className }: { name: IconName; size?: number; className?: string }) {
  const Glyph = icons[name]
  return <Glyph aria-hidden="true" focusable="false" size={size} strokeWidth={1.8} className={className} />
}
