# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
#
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy ASP.NET Core app to Azure Web App - careeros-api

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/main_careeros-api.yml"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore dependencies
        run: dotnet restore server/server.csproj

      - name: Build
        run: dotnet build server/server.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish server/server.csproj \
          --configuration Release \
          --output ${{ env.DOTNET_ROOT }}/myapp \
          --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0883095C0B6E41E5BC88C552E4F32246 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80C35AF1BF464337BFE5C575578AF6AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8B4E478BA2242C0816A9797A48AF88E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "careeros-api"
          slot-name: "Production"
          package: ./publish
